import io
from pathlib import Path

p = Path(r"c:\Users\Michal\Documents\GitHub\openevolve\examples\merge\initial_program.py")
text = p.read_text(encoding='utf-8', errors='replace')
# Remove unicode replacement characters and convert non-breaking spaces
clean = text.replace('\ufffd', ' ').replace('\u00a0', ' ')
# Replace repeated spaces/tabs generated by broken characters with single spaces where appropriate
# But keep indentation by preserving leading whitespace on each line
lines = []
for ln in clean.splitlines():
    # preserve leading indentation
    leading = ''
    for ch in ln:
        if ch in (' ', '\t'):
            leading += ch
        else:
            break
    body = ln[len(leading):]
    # collapse multiple internal replacement remnants
    body = body.replace('\t', '    ')
    lines.append(leading + body)

new_text = '\n'.join(lines)
# Write back
p.write_text(new_text, encoding='utf-8')
print('Sanitized', p)
